version: "3"

services: 
  redis:
    container_name: redis
    image: redis
    expose: 
      - 6379

  app: 
    container_name: atlan-challenge
    build: .
    ports:
      - 3000:3000
    links:
      - redis:redis
    environment: 
      - REDIS_URL=redis://redis
      - NODE_ENV=development
      - PORT=3000
    

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
